### ISSUE TITLE
Compliance for OSS

### ISSUE THREAD

**Issue by MahatiC** [microsoft/azure-privacy-sandbox-demo#1]
- Add `CONTRIBUTING.md` at the root
- Include this in each source file
`// Copyright (c) Microsoft Corporation.`
`// Licensed under the MIT license.`
- Describe the third-party OSS and its license in the NOTICE file. Do not remove any license information from the third-party code.

**Comment by DomAyre** [comment]
Added copyrights and NOTICE file at: https://github.com/microsoft/azure-privacy-sandbox-demo/commit/368a8fcc186c072be536e35879b9d08d7314e2bb
